// <auto-generated />
namespace Registration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class usercs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usercs));
        
        string IMigrationMetadata.Id
        {
            get { return "201401252110333_user.cs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
